In [5]:
from draft_boards import DraftBoard
from fantasyprosdata import FantasyProsData

In [2]:
fvd = FantasyProsData(scoring="PPR", dynasty=False)

In [3]:
proj = fvd.projected_points(1)

In [4]:
proj.head(40)

                 Player Position Team  FPTS
0       Patrick Mahomes       QB   KC 23.70
1         Lamar Jackson       QB  BAL 22.60
2           Jalen Hurts       QB  PHI 22.30
3            Josh Allen       QB  BUF 21.40
4            Joe Burrow       QB  CIN 20.10
5        Justin Herbert       QB  LAC 20.10
6         Justin Fields       QB  PIT 20.00
7           Tyreek Hill       WR  MIA 19.30
8       Trevor Lawrence       QB  JAC 19.30
9         Austin Ekeler       RB  WAS 19.30
10     Justin Jefferson       WR  MIN 19.20
11           Geno Smith       QB  SEA 19.20
12       Deshaun Watson       QB  CLE 19.00
13         Daniel Jones       QB  NYG 18.90
14         Kirk Cousins       QB  ATL 18.50
15       Russell Wilson       QB  PIT 18.40
16   Anthony Richardson       QB   ND 18.40
17  Christian McCaffrey       RB   SF 18.30
18         Dak Prescott       QB  DAL 18.20
19       Tua Tagovailoa       QB  MIA 18.00
20        Ja'Marr Chase       WR  CIN 17.90
21       Bijan Robinson       RB  ATL 17.80
22         Tony Pollard       RB  TEN 17.30
23          CeeDee Lamb       WR  DAL 17.10
24        Davante Adams       WR   LV 16.70
25    Amon-Ra St. Brown       WR  DET 16.70
26           Jared Goff       QB  DET 16.60
27        Aaron Rodgers       QB  NYJ 16.50
28       Saquon Barkley       RB  PHI 16.50
29           Sam Howell       QB  SEA 16.40
30          Josh Jacobs       RB   GB 16.00
31         Stefon Diggs       WR  HOU 15.90
32           Derek Carr       QB   NO 15.90
33        Derrick Henry       RB  BAL 15.90
34  Rhamondre Stevenson       RB   NE 15.70
35          Chris Olave       WR   NO 15.60
36       Baker Mayfield       QB   TB 15.60
37            Joe Mixon       RB  HOU 15.40
38        Kenny Pickett       QB  PHI 15.20
39       Garrett Wilson       WR  NYJ 15.20

In [6]:
db = DraftBoard("PPR")

In [7]:
db.get_draft_board().head(40)

                 Player Position  VOR Rank  ADP Rank  Tier
0   Christian McCaffrey       RB         2         1     1
1           CeeDee Lamb       WR         1         2     1
2           Tyreek Hill       WR         3         3     2
3         Ja'Marr Chase       WR         7         4     2
4      Justin Jefferson       WR         5         5     2
5        Bijan Robinson       RB         8         6     2
6           Breece Hall       RB         6         7     2
7            A.J. Brown       WR        10         8     2
8            Puka Nacua       WR         9         9     2
9        Garrett Wilson       WR        12        10     3
10      Marvin Harrison       WR        14        11     3
11         Drake London       WR        21        12     3
12         Jahmyr Gibbs       RB        29        13     2
13      Jonathan Taylor       RB        16        14     2
14        Davante Adams       WR        13        15     3
15          Chris Olave       WR        15        16     3
16         Nico Collins       WR        18        17     3
17        Brandon Aiyuk       WR        26        18     3
18        Jaylen Waddle       WR        34        19     3
19         Deebo Samuel       WR        23        20     3
20           Mike Evans       WR        19        21     3
21       Saquon Barkley       RB        11        22     2
22        DeVonta Smith       WR        27        23     3
23         Malik Nabers       WR        52        24     4
24          Cooper Kupp       WR        22        25     3
25        De'Von Achane       RB        43        26     3
26           DK Metcalf       WR        30        27     3
27             DJ Moore       WR        24        28     3
28       Kyren Williams       RB        20        29     2
29         Stefon Diggs       WR        31        30     3
30      Michael Pittman       WR        25        31     3
31        Derrick Henry       RB        36        32     3
32          Zay Flowers       WR        32        33     3
33            Tank Dell       WR        44        34     3
34         Travis Kelce       TE        17        35     1
35          Sam LaPorta       TE        28        36     1
36           Josh Allen       QB        50        37     1
37       Christian Kirk       WR        55        38     4
38       George Pickens       WR        56        39     4
39         Amari Cooper       WR        35        40     3

In [22]:
from pathlib import Path
import pandas as pd

base_path = "/Users/tylerbakely/Desktop/repos/NFL-Analysis/"
# for position in ["rb", "wr", "te"]:
report = (pd.read_csv(base_path + f"{position}_final_report_2023.csv") for position in ["rb", "wr", "te"])
data = pd.concat(report).reset_index(drop=True)

data.head()

,Unnamed: 0,player_name,position,season,full_year_score,full_year_tier,half_1_score,half_1_tier,half_2_score,half_2_tier,quarter_1_score,quarter_1_tier,quarter_2_score,quarter_2_tier,quarter_3_score,quarter_3_tier,final_6_score,final_6_tier,avg_score,avg_tier
0,0,C.McCaffrey,RB,2023,18.61,1,18.14,1.00,19.08,1.00,19.47,1.00,17.76,2.00,19.46,2.00,18.74,2.00,18.75,1.43
1,1,K.Williams,RB,2023,18.52,1,17.65,2.00,19.38,1.00,17.69,3.00,17.48,2.00,20.83,1.00,19.38,1.00,18.71,1.57
2,3,S.Barkley,RB,2023,17.17,2,17.95,1.00,16.73,3.00,17.20,4.00,18.50,1.00,17.40,3.00,16.45,5.00,17.34,2.71
3,2,A.Kamara,RB,2023,17.25,2,18.08,1.00,16.44,4.00,17.44,4.00,18.56,1.00,16.56,5.00,16.58,5.00,17.27,3.14
4,4,J.Jacobs,RB,2023,17.11,2,17.47,2.00,16.75,3.00,17.25,4.00,17.75,2.00,17.00,4.00,16.60,5.00,17.13,3.14

In [23]:
draft_board = db.get_draft_board()

draft_board["player_name_join"] = draft_board["Player"].apply(lambda x: f"{x.split()[0][0]}.{x.split()[1]}")

In [13]:
draft_board["Player"].apply(lambda x: f"{x.split()[0][0]}.{x.split()[1]}")

0      C.McCaffrey
1           C.Lamb
2           T.Hill
3          J.Chase
4      J.Jefferson
          ...
189        T.Kraft
190        N.Brown
191       T.Palmer
192       T.Higbee
193      T.Patrick
Name: Player, Length: 194, dtype: object

In [25]:
joined = draft_board.merge(data, left_on="player_name_join", right_on="player_name", how="left")
joined.drop(columns=["player_name", "position", "season", "Unnamed: 0", "player_name_join"], inplace=True)
joined.to_csv("ppr_new_draftboard_2024.csv")

In [21]:
data.head(20)

,Unnamed: 0,player_name,position,season,full_year_score,full_year_tier,half_1_score,half_1_tier,half_2_score,half_2_tier,quarter_1_score,quarter_1_tier,quarter_2_score,quarter_2_tier,quarter_3_score,quarter_3_tier,final_6_score,final_6_tier,avg_score,avg_tier
0,0,C.McCaffrey,RB,2023,18.61,1,18.14,1,19.08,1,19.47,1,17.76,2,19.46,2,18.74,2,18.75,1.43
1,1,K.Williams,RB,2023,18.52,1,17.65,2,19.38,1,17.69,3,17.48,2,20.83,1,19.38,1,18.71,1.57
2,3,S.Barkley,RB,2023,17.17,2,17.95,1,16.73,3,17.20,4,18.50,1,17.40,3,16.45,5,17.34,2.71
3,2,A.Kamara,RB,2023,17.25,2,18.08,1,16.44,4,17.44,4,18.56,1,16.56,5,16.58,5,17.27,3.14
4,4,J.Jacobs,RB,2023,17.11,2,17.47,2,16.75,3,17.25,4,17.75,2,17.00,4,16.60,5,17.13,3.14
5,6,R.White,RB,2023,16.83,3,16.71,3,17.31,2,16.47,5,15.77,6,17.29,3,17.09,4,16.78,3.71
6,7,J.Mixon,RB,2023,16.75,3,16.69,3,16.89,3,16.10,6,16.69,3,16.39,5,16.89,4,16.63,3.86
7,8,T.Etienne,RB,2023,16.63,3,17.25,2,16.08,4,16.38,5,17.72,2,16.53,5,16.22,6,16.69,3.86
8,5,T.Pollard,RB,2023,16.86,3,17.00,3,16.74,3,17.77,3,15.74,6,16.16,6,16.98,4,16.75,4.00
9,11,A.Ekeler,RB,2023,16.23,4,16.91,3,16.07,4,18.89,2,15.87,5,16.85,4,15.60,7,16.63,4.14
10,9,I.Pacheco,RB,2023,16.46,4,15.64,5,17.62,2,15.77,7,15.71,6,16.41,5,18.29,2,16.56,4.43
11,19,D.Montgomery,RB,2023,15.78,5,16.92,3,15.14,6,17.22,4,17.68,2,15.31,7,15.11,8,16.17,5.00
12,15,R.Stevenson,RB,2023,15.91,5,15.57,5,16.76,3,15.64,7,15.18,7,17.27,3,16.06,6,16.06,5.14
13,17,J.Gibbs,RB,2023,15.86,5,15.58,5,16.05,4,14.52,9,16.51,4,17.29,3,15.74,7,15.94,5.29
14,18,D.Henry,RB,2023,15.84,5,16.02,4,15.87,4,15.70,7,15.92,5,16.01,6,16.09,6,15.92,5.29
15,12,B.Hall,RB,2023,16.16,4,15.37,6,16.82,3,13.79,11,16.34,4,15.87,6,17.24,3,15.94,5.29
16,16,D.Swift,RB,2023,15.89,5,16.40,4,15.46,5,16.12,6,16.36,4,16.04,6,15.11,8,15.91,5.43
17,13,A.Jones,RB,2023,16.00,5,15.53,5,16.71,3,14.83,8,14.14,9,15.39,7,17.47,3,15.73,5.71
18,10,J.Conner,RB,2023,16.32,4,15.35,6,16.93,3,16.08,6,13.37,11,15.42,7,17.33,3,15.83,5.71
19,14,R.Mostert,RB,2023,15.92,5,15.68,5,16.13,4,15.81,7,15.18,7,15.93,6,16.16,6,15.83,5.71

In [7]:
import pandas as pd

# dynasty_adp = pd.read_csv("sleeper_adp(1).csv")[["Player", "Team", "Position", "Dynasty SF ADP"]].sort_values("Dynasty SF ADP")
# dynasty_adp["ADP Rank"] = dynasty_adp["Dynasty SF ADP"].rank()

In [11]:
dynasty_adp = dynasty_adp.merge(tiers, on=["Player"], how="left")

In [13]:
dynasty_adp.to_csv("dynasty_draftboard.csv", index=False)

In [8]:
db.get_draft_board()

                  Player Position  VOR Rank  ADP Rank  Tier
0    Christian McCaffrey       RB         2         1     1
1            CeeDee Lamb       WR         1         2     1
2            Tyreek Hill       WR         3         3     2
3          Ja'Marr Chase       WR         7         4     2
4       Justin Jefferson       WR         5         5     2
..                   ...      ...       ...       ...   ...
189         Tucker Kraft       TE       194       190     6
190           Noah Brown       WR       182       191     8
191          Trey Palmer       WR       185       192     8
192         Tyler Higbee       TE       181       193     6
193          Tim Patrick       WR       171       194     8

[194 rows x 5 columns]

In [12]:
tiers.to_csv("tiers.csv", index=False)

In [2]:
from datetime import datetime

print(datetime.now())

2023-08-30 23:31:42.435803